###

# Post new request
POST http://127.0.0.1:8000/api/requests
Accept: application/json
Content-Type: application/json

{
    "vin": "4Y1SL65848Z411439",
    "email": "john@doe.com"
}

###
# Get request by UUID

GET http://127.0.0.1:8000/api/requests/aecc3309-4eb0-4cc1-814c-71941403c6b8
Accept: application/json


###
# Get all requests
GET http://127.0.0.1:8000/api/requests
Accept: application/json


###
# Technical endpoint - project health
GET http://127.0.0.1:8000/api/health
Accept: application/json